import logging
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import cast, Any

from modosaic.core.modalities import Modalities
from modosaic.core.record import ImageRecord
from modosaic.core.validation_constraint import ValidationConstraint
from modosaic.core.validation_result import ValidationResult
from modosaic.core.validator import ModalityValidator

logger = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class ValidatorStep[T, U]:
    """Configured execution wrapper for a modality validator.

    Attributes:
        validator: Validator object to run.
        dependencies: Mapping from validator keyword arguments to earlier
            modality outputs.
        name: Optional display name. Defaults to the validator class name.
        constraint: Optional quality gate applied to the validator value.
    """

    validator: ModalityValidator[T, U]
    dependencies: Mapping[str, Modalities] = field(default_factory=dict)
    name: str | None = None
    constraint: ValidationConstraint[U] | None = None

    @property
    def validator_name(self) -> str:
        """Return the configured display name for the validator."""
        return self.name or self.validator.__class__.__name__

    def validate(
            self,
            record: ImageRecord,
            generated: T,
            generated_modalities: Mapping[Modalities, Any],
    ) -> ValidationResult[U]:
        """Run the validator and apply the optional constraint.

        Args:
            record: Input image record.
            generated: Output generated by the current modality.
            generated_modalities: Accepted outputs from earlier modalities,
                used to satisfy dependency mappings.

        Returns:
            Raw or constrained validation result.
        """
        logger.debug(f"Running validator {self.validator_name} for record sample {record.sample_id}")
        kwargs = {
            name: generated_modalities.get(modality)
            for name, modality in self.dependencies.items()
        }
        if self.dependencies:
            logger.debug(
                f"Validator {self.validator_name} dependencies for record sample {record.sample_id}: "
                f"{self.dependencies}"
            )

        if kwargs:
            value = cast(Any, self.validator).validate(record, generated, **kwargs)
        else:
            value = self.validator.validate(record, generated)

        if self.constraint:
            score, passed = self.constraint.evaluate(value)
            logger.debug(
                f"Validator {self.validator_name} scored {score} for record sample {record.sample_id}; "
                f"passed={passed}"
            )
            return ValidationResult(
                validator_name=self.validator_name,
                value=value,
                score=score,
                score_name=self.constraint.score_name,
                minimum=self.constraint.minimum,
                passed=passed,
            )

        logger.debug(f"Validator {self.validator_name} completed for record sample {record.sample_id}")
        return ValidationResult(
            validator_name=self.validator_name,
            value=value,
        )
